SELECT YEAR, (maxes.m - ECOLI_DATA.SIZE_OF_COLONY) as YEAR_DEV, ID
FROM ECOLI_DATA LEFT JOIN 
(SELECT YEAR, MAX(SIZE_OF_COLONY) as m
FROM (SELECT SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) as YEAR FROM ECOLI_DATA) as a
GROUP BY YEAR) as maxes
on YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = maxes.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC